# 预备知识
## 数据操作
#### PyTorch的导入

In [1]:
import torch

#### 张量的基本创建方式
张量就是多种维度的数据，无论是0维（单个数据）、一维（数组）甚至更多维都可以视作一个。在numpy里是np.ndarray，在torch里是torch.arange.

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

这段代码创建了一个12个元素的行向量，并自动赋值为0~11，默认是整数，当然也可以指定元素类型。

torch.arange默认只能创建一维张量，可以使用reshape改变形状，然后用shape检查大小

In [3]:
x = x.reshape(3, 4)
x.shape

torch.Size([3, 4])

如果只关注总元素，也可以使用numel函数

In [4]:
x.numel()

12

arange默认创造的是一个一维的带标号的张量，如果我希望创建一个任意维度的全某任意值的张量，可以使用zeros或者ones

In [5]:
x = torch.zeros(3, 4)
x = torch.ones(3, 4)
x = x * 3
x

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

如果希望得到一个随机数组成的张量，可以使用randn，提供一个符合$X \sim \mathcal{N}(0, 1)$的数组

In [6]:
x = torch.randn(3, 4)
x

tensor([[ 1.4100,  0.0656,  2.0557,  0.1562],
        [ 1.1418, -0.3625, -0.0168, -0.1952],
        [-0.9922, -1.8722,  1.4285,  0.8121]])

也可以直接使用tensor去默认初始化数组

In [7]:
x = torch.tensor([[3, 2, 1],
                  [3, 4, 5]])
x

tensor([[3, 2, 1],
        [3, 4, 5]])

#### 张量的基本运算（运算符）
常见的运算符如加减乘除幂都可以升级为张量内的按元素运算，如下

In [8]:
x = torch.ones(3, 4) *3
y = torch.ones(3, 4) *2
x ** y

tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]])

常见的运算也支持逐元素运算

In [9]:
x = torch.exp(torch.arange(4))
x#求e的幂

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

可以通过**连结**操作把两个某个维度数量相同的张量连在一起

In [12]:
X = torch.arange(12, dtype = torch.float32).reshape(3, 4) #该张量在0维数量为3
Y = torch.tensor([[1.0, 2], [3, 4.1], [4, 3]]) #该张量在0维数量同样为3
torch.cat((X, Y), dim = 1) #以1维链接，要求除了1维外的所有元素数必须相同，这里只有0维相同

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  1.0000,  2.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  3.0000,  4.1000],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  4.0000,  3.0000]])

使用表达式$==$判定两个张量是否等价

In [16]:
X = torch.arange(8, dtype = torch.float32).reshape(2, 4)
Y = torch.tensor([[2, 1, 2, 3], [4, 6, 7, 8]])
X == Y

tensor([[False,  True,  True,  True],
        [ True, False, False, False]])

#### 广播机制
广播机制作用于两个尺寸不相同的张量进行二元运算时。进行运算时，两个元素会先通过复制的方式扩展直到尺寸相同，后逐元素运算。
要求：待拓展的元素的待拓展维度原元素数必须是1

In [18]:
a = torch.arange(3).reshape(1, 3)
b = torch.arange(2).reshape(2, 1)
print(a)
print(b)
print(a + b)

tensor([[0, 1, 2]])
tensor([[0],
        [1]])
tensor([[0, 1, 2],
        [1, 2, 3]])


#### 索引与切片
与Python的list相同

#### 内存的使用
Python令人诟病的引用操作会导致内存的浪费，如

In [22]:
x = torch.arange(3)
y = torch.arange(3)
before = id(y)
y = x + y
id(y) == before

False

可以使用切片表示法指定部分地方的内存去使用，如下所示

In [23]:
# 方法1，构造新的内存空间，使用切片法
z = torch.zeros_like(y) #不同于zeros的是，这里的Z的全部关键属性包括数据类型、存储的设备（是主存还是显存）等等都与y一样，只是元素大小全0
z[:] = x + y
# 方法2，原地操作
x += y

In [ ]:
####