# 预备知识
## 数据操作
#### PyTorch的导入

In [1]:
import torch

#### 张量的基本创建方式
张量就是多种维度的数据，无论是0维（单个数据）、一维（数组）甚至更多维都可以视作一个。在numpy里是np.ndarray，在torch里是torch.tensor.这里用arange创建一个一维张量。

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

这段代码创建了一个12个元素的行向量，并自动赋值为0~11，默认是整数，当然也可以指定元素类型。

torch.arange默认只能创建一维张量，可以使用reshape改变形状，然后用shape检查大小

In [3]:
x = x.reshape(3, 4)
x.shape

torch.Size([3, 4])

如果只关注总元素，也可以使用numel函数

In [4]:
x.numel()

12

arange默认创造的是一个一维的带标号的张量，如果我希望创建一个任意维度的全某任意值的张量，可以使用zeros或者ones

In [5]:
x = torch.zeros(3, 4)
x = torch.ones(3, 4)
x = x * 3
x

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

如果希望得到一个随机数组成的张量，可以使用randn，提供一个符合$X \sim \mathcal{N}(0, 1)$的数组

In [7]:
x = torch.randn(3, 4)
x

tensor([[-0.4980,  2.8402,  1.1826,  0.4852],
        [-0.2784,  0.1078, -0.1498,  0.0975],
        [-1.0000,  0.2837, -0.0587,  0.3464]])

也可以直接使用tensor去默认初始化数组

In [8]:
x = torch.tensor([[3, 2, 1],
                  [3, 4, 5]])
x

tensor([[3, 2, 1],
        [3, 4, 5]])

#### 张量的基本运算（运算符）
常见的运算符如加减乘除幂都可以升级为张量内的按元素运算，如下

In [9]:
x = torch.ones(3, 4) *3
y = torch.ones(3, 4) *2
x ** y

tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]])

常见的运算也支持逐元素运算

In [10]:
x = torch.exp(torch.arange(4))
x#求e的幂

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

可以通过**连结**操作把两个某个维度数量相同的张量连在一起

In [11]:
X = torch.arange(12, dtype = torch.float32).reshape(3, 4) #该张量在0维数量为3
Y = torch.tensor([[1.0, 2], [3, 4.1], [4, 3]]) #该张量在0维数量同样为3
torch.cat((X, Y), dim = 1) #以1维链接，要求除了1维外的所有元素数必须相同，这里只有0维相同

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  1.0000,  2.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  3.0000,  4.1000],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  4.0000,  3.0000]])

使用表达式$==$判定两个张量是否等价

In [12]:
X = torch.arange(8, dtype = torch.float32).reshape(2, 4)
Y = torch.tensor([[2, 1, 2, 3], [4, 6, 7, 8]])
X == Y

tensor([[False,  True,  True,  True],
        [ True, False, False, False]])

#### 广播机制
广播机制作用于两个尺寸不相同的张量进行二元运算时。进行运算时，两个元素会先通过复制的方式扩展直到尺寸相同，后逐元素运算。
要求：待拓展的元素的待拓展维度原元素数必须是1

In [13]:
a = torch.arange(3).reshape(1, 3)
b = torch.arange(2).reshape(2, 1)
print(a)
print(b)
print(a + b)

tensor([[0, 1, 2]])
tensor([[0],
        [1]])
tensor([[0, 1, 2],
        [1, 2, 3]])


#### 索引与切片
与Python的list相同

#### 内存的使用
Python令人诟病的引用操作会导致内存的浪费，如

In [14]:
x = torch.arange(3)
y = torch.arange(3)
before = id(y)
y = x + y
id(y) == before

False

可以使用切片表示法指定部分地方的内存去使用，如下所示

In [15]:
# 方法1，构造新的内存空间，使用切片法
z = torch.zeros_like(y) #不同于zeros的是，这里的Z的全部关键属性包括数据类型、存储的设备（是主存还是显存）等等都与y一样，只是元素大小全0
z[:] = x + y
# 方法2，原地操作
x += y

#### 与其他python变量互相转换

In [16]:
import numpy
a = x.numpy()
b = torch.tensor(a)

## 数据预处理
#### 读取数据集
##### 写入数据集（CSV）



In [20]:
import os

os.makedirs(os.path.join("..", 'data'), exist_ok = True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

##### 使用pandas导入csv文件
可以使用`read_csv`函数

In [21]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)
print(type(data))

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
<class 'pandas.DataFrame'>


## 线性代数
$L_p$范数：$\sqrt[n]{{\left|a_1\right|}^n+{\left|a_2\right|}^n+...+{\left|a_m\right|}^n}$

其余略
## 微积分
略

## 自动微分
自动微分通过更新计算图记录数据的流通过程获得精确导数解。举例说明：
```python
    y = 2 * torch.dot(x, x)  #捕获x的操作：先平方，再乘2
    y = y * y  #捕获y的操作，平方
```
最后套入链式法则获得最终解 y'=16x^3，回代x得到偏导
**x在这里是列向量**

#### 演示

In [1]:
import torch

x = torch.arange(4.0, requires_grad=True) #第二个参数代表该变量需要被计算图覆盖
y = 2 * torch.dot(x, x)
y.backward() #反向传播计算x的导数
x.grad


tensor([ 0.,  4.,  8., 12.])

从上可以得出y反向传播得到的解实际上是```4*x```

In [3]:
x.grad == 4 * x

tensor([True, True, True, True])

换个例子

In [4]:
x.grad.zero_() #给x的梯度清零
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

#### 非标量变量的反向传播
torch的自动微分只针对标量对标量或向量的求导，倘若待求导的是向量对向量的求导，可以使用求和的方式计算各个导数（雅各比矩阵非主对角线部分全为0）

In [5]:
x.grad.zero_()
y = x * x
y.sum().backward() #这里先求和后反向传播
x.grad

tensor([0., 2., 4., 6.])

#### 分离计算
使用detach可以把某个参数的计算图剥离，只看它的数值。
例如```z = z(x, y)```，其中```y = y(x)```，但是我只想计算z忽略y的关于x的导数，此时可以用detach，如

In [7]:
x.grad.zero_()
y = x * x
u = y.detach() #此时已经忽略了y关于x的计算图了
z = u * x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

#### 计算图
计算图的本质是DAG，计算的梯度只关心子叶节点，如示例

In [8]:
y = torch.arange(4.0, requires_grad=True) * x
z = y * x
print(x.grad)
print(y.grad)

tensor([0., 1., 4., 9.])
None


C:\Users\YootM\AppData\Local\Temp\ipykernel_36888\673455101.py:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:498.)
  print(y.grad)


y作为非子节点，不具有梯度。实际的叶节点是y中的arange和x

#### Python流程控制下的梯度计算
自动微分在受Python控制后依然可以正常计算梯度

## 概率论
略
## 查找文档
略